### ISSUE TITLE
time out issue

### ISSUE THREAD

**Issue by biskit** [firecracker-microvm/firecracker-containerd#72] opened 2019-01-20 00:10 UTC
i've followed the script and the getting started guide. 

using the script (building local version of containerd, runc, firecracker and firecracker-containerd).

trying on
`Linux ub18 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

running `sudo PATH=$PATH /usr/local/bin/containerd` in one window and `sudo /usr/local/bin/naive_snapshotter      -address /var/run/firecracker-containerd/naive-snapshotter.sock      -path /var/lib/firecracker-containerd/naive      -debug` in another.

when i do `sudo ctr run --snapshotter firecracker-naive --runtime aws.firecracker --tty docker.io/library/busybox:latest busybox-test` i get `ctr: Firecracker did not create API socket ./firecracker.sock: context deadline exceeded: unknown`

any ideas why?

**Comment by mxpv** [comment] 2019-01-20 02:48
Hey. You also need to register a proxy plugin in containerd's configuration file. Here is an [example](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/snapshotter/cmd/devmapper/README.md#installation) how. Also make sure that `address = "/var/run/firecracker-snapshotter.sock"` field points to same socket location.

**Comment by biskit** [comment] 2019-01-20 02:59
Believe i have registered the naive snapshotter as the documentation states
in the quickstart...

**Comment by biskit** [comment] 2019-01-20 14:42
this is what i have in /etc/containerd/config.toml

```
@ub18:~$ cat /etc/containerd/config.toml 
disabled_plugins = ["cri"]
[proxy_plugins]
  [proxy_plugins.firecracker-naive]
    type = "snapshot"
    address = "/var/run/firecracker-containerd/naive-snapshotter.sock"
```

**Comment by mxpv** [comment] 2019-01-21 18:18
I'm running same commands, but can't reproduce the problem. Could you please check which revisions of [firecracker-go-sdk](https://github.com/firecracker-microvm/firecracker-go-sdk) and [firecracker-containerd](https://github.com/firecracker-microvm/firecracker-containerd) are you using? Also would be nice to look at `containerd` log output.

**Comment by biskit** [comment] 2019-01-21 18:31
ofcourse:
```
bs@ub18:~$ stat /var/run/firecracker-containerd/
  File: /var/run/firecracker-containerd/
  Size: 40        	Blocks: 0          IO Block: 4096   directory
Device: 16h/22d	Inode: 66          Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-01-19 13:09:48.400567736 -0600
Modify: 2019-01-21 10:50:07.542299413 -0600
Change: 2019-01-21 10:50:07.542299413 -0600
 Birth: -
bs@ub18:~$ ls -l /var/run/firecracker-containerd/
total 0
```

**Comment by xibz** [comment] 2019-01-21 18:46
@biskit - What does the Firecracker config look like? And ensure you can stat the files listed in the config as well

```bash
cat /etc/containerd/firecracker-runtime.json
```

**Comment by biskit** [comment] 2019-01-21 18:56
```
bs@ub18:~/firecracker-containerd$ cat /etc/containerd/firecracker-runtime.json 
{
  "firecracker_binary_path": "/usr/local/bin/firecracker",
  "socket_path": "/tmp/firecracker.sock",
  "kernel_image_path": "/var/lib/firecracker-containerd/runtime/hello-vmlinux.bin",
  "kernel_args": "console=ttyS0 noapic reboot=k panic=1 pci=off nomodules rw",
  "root_drive": "/var/lib/firecracker-containerd/runtime/hello-rootfs.ext4",
  "cpu_count": 1,
  "cpu_template": "T2",
  "console": "stdio",
  "log_fifo": "/tmp/fc-logs.fifo",
  "log_level": "Debug",
  "metrics_fifo": "/tmp/fc-metrics.fifo"
}
```

i have used a fixed location for `socket_path` just to make sure i know where it is. i have deleted them before running the `ctr` command.

and all files seem accessible...

**Comment by xibz** [comment] 2019-01-21 20:33
@biskit - No problem! Thank you for giving us the information we need to help debug this :). Also what version of firecracker are you using? Ensure you are using `v0.12.0`

```bash
firecracker --version
```

**Comment by biskit** [comment] 2019-01-21 20:35
well lmk if this could be the problem... i'll checkout v0.12.0 build/try

```
bs@ub18:~$ firecracker --version
firecracker 0.13.0
bs@ub18:~$ which firecracker
/usr/local/bin/firecracker
```

**Comment by biskit** [comment] 2019-01-21 20:48
update. did a build with v0.12.0 (static musl), copied it over and
1. ran containerd and snapshotter in debug mode.
2. ran ctr command
took a little while, and i'm now getting a prompt.

attaching all the logs so it'll be helpful for others.

```
bs@ub18:~$ sudo /usr/local/bin/naive_snapshotter      -address /var/run/firecracker-containerd/naive-snapshotter.sock      -path /var/lib/firecracker-containerd/naive      -debug
INFO[0000] creating naive snapshotter                    root=/var/lib/firecracker-containerd/naive
INFO[0000] running gRPC server                           unix_addr=/var/run/firecracker-containerd/naive-snapshotter.sock
DEBU[0013] walk                                         
DEBU[0013] remove                                        key=default/12/busybox-test
DEBU[0017] stat                                          key="default/2/sha256:683f499823be212bf04cb9540407d8353803c25d0d9eb5f2fdb62786d8b95ead"
DEBU[0017] prepare                                       key=default/13/busybox-test parent="default/2/sha256:683f499823be212bf04cb9540407d8353803c25d0d9eb5f2fdb62786d8b95ead"
INFO[0017] copying data from parent snapshot 2          
DEBU[0023] mounts                                        key=default/13/busybox-test
DEBU[0030] mounts                                        key=default/13/busybox-test
DEBU[0037] stat                                          key="default/2/sha256:683f499823be212bf04cb9540407d8353803c25d0d9eb5f2fdb62786d8b95ead"
DEBU[0041] walk                                         
DEBU[0041] remove                                        key=default/13/busybox-test
DEBU[0042] stat                                          key="default/2/sha256:683f499823be212bf04cb9540407d8353803c25d0d9eb5f2fdb62786d8b95ead"
DEBU[0042] prepare                                       key=default/14/busybox-test parent="default/2/sha256:683f499823be212bf04cb9540407d8353803c25d0d9eb5f2fdb62786d8b95ead"
INFO[0042] copying data from parent snapshot 2          
DEBU[0047] mounts                                        key=default/14/busybox-test
DEBU[0054] mounts                                        key=default/14/busybox-test
```

```
^Cbs@ub18:~$ sudo PATH=$PATH /usr/local/bin/containerd
INFO[2019-01-21T14:39:33.169558958-06:00] starting containerd                           revision=9b32062dc1f5a7c2564315c269b5059754f12b9d version=v1.2.1
INFO[2019-01-21T14:39:33.170374429-06:00] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2019-01-21T14:39:33.170440986-06:00] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
WARN[2019-01-21T14:39:33.170821726-06:00] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
INFO[2019-01-21T14:39:33.170864861-06:00] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2019-01-21T14:39:33.172612945-06:00] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2019-01-21T14:39:33.172694294-06:00] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2019-01-21T14:39:33.172859237-06:00] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
WARN[2019-01-21T14:39:33.173305536-06:00] failed to load plugin io.containerd.snapshotter.v1.zfs  error="path /var/lib/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[2019-01-21T14:39:33.173350765-06:00] loading plugin "io.containerd.snapshotter.v1.firecracker-naive"...  type=io.containerd.snapshotter.v1
INFO[2019-01-21T14:39:33.173436071-06:00] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2019-01-21T14:39:33.173482959-06:00] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
WARN[2019-01-21T14:39:33.173524828-06:00] could not use snapshotter zfs in metadata plugin  error="path /var/lib/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[2019-01-21T14:39:33.173757918-06:00] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2019-01-21T14:39:33.173816743-06:00] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2019-01-21T14:39:33.173885978-06:00] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2019-01-21T14:39:33.173926863-06:00] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2019-01-21T14:39:33.173979377-06:00] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2019-01-21T14:39:33.174023958-06:00] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2019-01-21T14:39:33.174048392-06:00] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2019-01-21T14:39:33.174075881-06:00] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2019-01-21T14:39:33.174106177-06:00] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2019-01-21T14:39:33.174144295-06:00] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2019-01-21T14:39:33.174217888-06:00] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2019-01-21T14:39:33.174505847-06:00] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2019-01-21T14:39:33.175247992-06:00] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2019-01-21T14:39:33.175296153-06:00] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2019-01-21T14:39:33.175364814-06:00] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175398720-06:00] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175430745-06:00] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175478329-06:00] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175515845-06:00] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175552473-06:00] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175586134-06:00] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175626857-06:00] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175665680-06:00] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2019-01-21T14:39:33.175766332-06:00] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175823109-06:00] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175864008-06:00] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.175904476-06:00] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2019-01-21T14:39:33.176141607-06:00] serving...                                    address="/run/containerd/containerd.sock"
INFO[2019-01-21T14:39:33.176183704-06:00] containerd successfully booted in 0.007353s  
time="2019-01-21T14:40:00.558075923-06:00" level=info msg="starting signal loop" namespace=default path=/run/containerd/io.containerd.runtime.v2.task/default/busybox-test pid=29351
time="2019-01-21T14:40:00.559157727-06:00" level=info msg="starting VM" runtime=aws.firecracker
time="2019-01-21T14:40:00.559291924-06:00" level=error msg="failed to start VM" error="socket /tmp/firecracker.sock already exists" runtime=aws.firecracker
time="2019-01-21T14:40:24.204607217-06:00" level=info msg="starting signal loop" namespace=default path=/run/containerd/io.containerd.runtime.v2.task/default/busybox-test pid=29422
time="2019-01-21T14:40:24.205151328-06:00" level=info msg="starting VM" runtime=aws.firecracker
time="2019-01-21T14:40:24.205356626-06:00" level=info msg="starting instance" runtime=aws.firecracker
time="2019-01-21T14:40:24.219644980-06:00" level=info msg="Attaching drive /dev/loop5, slot 0, root false."
time="2019-01-21T14:40:24.220485957-06:00" level=info msg="Attaching drive /var/lib/firecracker-containerd/runtime/hello-rootfs.ext4, slot root-drive, root true."
time="2019-01-21T14:40:24.412833022-06:00" level=info msg="calling agent" runtime=aws.firecracker
time="2019-01-21T14:40:24.412936310-06:00" level=warning msg="vsock dial failed (attempt 1 of 5), will retry in 100ms" error="no such device" runtime=aws.firecracker
time="2019-01-21T14:40:24.513139412-06:00" level=warning msg="vsock dial failed (attempt 2 of 5), will retry in 200ms" error="no such device" runtime=aws.firecracker
time="2019-01-21T14:40:24.719543831-06:00" level=warning msg="vsock dial failed (attempt 3 of 5), will retry in 400ms" error="connection reset by peer" runtime=aws.firecracker
time="2019-01-21T14:40:25.124049360-06:00" level=warning msg="vsock dial failed (attempt 4 of 5), will retry in 800ms" error="connection reset by peer" runtime=aws.firecracker
time="2019-01-21T14:40:25.924465738-06:00" level=info msg="creating clients" runtime=aws.firecracker
time="2019-01-21T14:40:25.924554491-06:00" level=info msg="creating task 'busybox-test'" runtime=aws.firecracker
time="2019-01-21T14:43:19.891148341-06:00" level=info msg="successfully created task with pid 992" runtime=aws.firecracker
```

```
bs@ub18:~$ sudo ctr run --snapshotter firecracker-naive --runtime aws.firecracker --tty docker.io/library/busybox:latest busybox-test
/ # pwd
/
/ # ls
bin   dev   etc   home  proc  root  run   sys   tmp   usr   var
/ # id
uid=0(root) gid=0(root) groups=10(wheel)
/ # 
```

```
bs@ub18:~$ ps -ef|grep fire|grep -v grep
root     29279  9643  0 14:39 pts/1    00:00:00 sudo /usr/local/bin/naive_snapshotter -address /var/run/firecracker-containerd/naive-snapshotter.sock -path /var/lib/firecracker-containerd/naive -debug
root     29280 29279  0 14:39 pts/1    00:00:02 /usr/local/bin/naive_snapshotter -address /var/run/firecracker-containerd/naive-snapshotter.sock -path /var/lib/firecracker-containerd/naive -debug
root     29392  9241  0 14:40 pts/2    00:00:00 sudo ctr run --snapshotter firecracker-naive --runtime aws.firecracker --tty docker.io/library/busybox:latest busybox-test
root     29393 29392  0 14:40 pts/2    00:00:00 ctr run --snapshotter firecracker-naive --runtime aws.firecracker --tty docker.io/library/busybox:latest busybox-test
root     29422     1  0 14:40 pts/0    00:00:02 /usr/local/bin/containerd-shim-aws-firecracker -namespace default -address /run/containerd/containerd.sock -publish-binary /usr/local/bin/containerd
root     29431 29422  5 14:40 pts/0    00:00:23 /usr/local/bin/firecracker --api-sock /tmp/firecracker.sock
```

**Comment by xibz** [comment] 2019-01-21 21:33
`/tmp/fire/tmp/firecracker.sock` needs to be deleted. That file cannot be present when starting the container. Please let us know if that helps!

**Comment by biskit** [comment] 2019-01-21 21:37
@xibz I've been able to successfully start a vm with firecracker v0.12.0 as the vm. that was the problem.

v0.13.0 does not work and as you say, I had to remove /tmp/firecracker.sock for it to run.

**Comment by xibz** [comment] 2019-01-21 22:07
@biskit awesome! I am going to go ahead and close this issue. We have another [issue](https://github.com/firecracker-microvm/firecracker-go-sdk/issues/51) tracking support for 0.13.0. Please let us know if you have any more issues!

**Closed by xibz** 2019-01-21 22:07 UTC
Labels: kind/question
