### ISSUE TITLE
Figure out why cri plugin must be disabled

### ISSUE THREAD

**Issue by IRCody** [firecracker-microvm/firecracker-containerd#35] opened 2018-12-03 19:08 UTC
If the cri plugin is enabled, our runtime causes errors upon exiting:

```
INFO[2018-12-03T11:02:09.030879139-08:00] TaskExit event &TaskExit{ContainerID:,ID:,Pid:224,ExitStatus:0,ExitedAt:2018-12-03 19:01:50.016792753 +0000 UTC,}
ERRO[2018-12-03T11:02:09.030966305-08:00] Failed to handle backOff event &TaskExit{ContainerID:,ID:,Pid:224,ExitStatus:0,ExitedAt:2018-12-03 19:01:50.016792753 +0000 UTC,} for   error="can't find container for TaskExit event: Prefix can't be empty"
```

The error "Prefix can't be empty" appears to be coming from a [pkg](https://github.com/moby/moby/blob/master/pkg/truncindex/truncindex.go#L17) in moby that is used by the [cri plugin](https://github.com/containerd/cri/blob/e312635396a13bc67cc5c9f3e5f873dc92cfc891/pkg/store/sandbox/sandbox.go#L64).

It's unclear why because AFAIK we are not invoking any cri functionality but having the plugin enabled seems to change the code path for exiting in some way.

**Comment by mikebrow** [comment] 2018-12-04 17:09
What containerd namespace did you use for the containers?

**Comment by mikebrow** [comment] 2018-12-04 17:20
Please turn the log to debug and let's see what the output looks like :-)

**Comment by mikebrow** [comment] 2018-12-04 17:34
See.. https://github.com/containerd/containerd/blob/master/api/events/task.pb.go#L75-L81

if TaskExit.ID is empty the code throws the empty error

**Comment by mikebrow** [comment] 2018-12-04 17:44
The issue is the containerid may be a dup.. so.. we use ID as a unique identifier to pick between the dups.

We generate it with this code:
// GenerateID generates a random unique id.
func GenerateID() string {
	b := make([]byte, 32)
	rand.Read(b)
	return hex.EncodeToString(b)
}

**Comment by mikebrow** [comment] 2018-12-04 17:45
I suppose we could ignore any task exit with missing ID.

**Comment by IRCody** [comment] 2018-12-04 19:34
So there is a containerId and ID. If you run via something like:
`./ctr run --runtime aws.firecracker --snapshotter firecracker-snapshotter --tty docker.io/library/alpine:latest 1234 /bin/sh`

The containerId should be 1234. Where is the ID for the TaskExitEvent expected to come form in this case?

It's possible we are not correctly setting the ID in the TaskExitEvent but it's not clear to me exactly what it should be or where we would get it. Is this something containerd/cri would generate? Is it passed to the runtime? I

**Comment by mikebrow** [comment] 2018-12-04 20:05
right now we generate it as a random value see above.. But the issue pointed out a potential issue in so far as we were not filtering for namespace. So I've pushed a fix for this.

**Comment by IRCody** [comment] 2018-12-04 20:13
Thanks for submitting a fix. 

I saw the above about how the ID is generated but not how it would be passed to the runtime (where we could make use of it in a TaskExitEvent). It's a little confusing b/c there are a few id's that are passed through at various points: https://github.com/containerd/containerd/blob/master/runtime/v2/task/shim.proto

The id for these seems to be the ContainerID not the ID referenced here. I guess I am curious to how a runtime could get the correct ID to pass through the TaskExitEvent.

We are also definitely not handling TaskExitEvent id's correctly here: https://github.com/firecracker-microvm/firecracker-containerd/blob/master/runtime/service.go#L224-L225
 since AFAIK s.id is never assigned. It should probably be assigned during createTask around here: https://github.com/firecracker-microvm/firecracker-containerd/blob/master/runtime/service.go#L152.

**Comment by mikebrow** [comment] 2018-12-04 21:19
still working on the proper filter.. looks like subscribe filters are only setup to do or this namespace not and this namespace

**Comment by mikebrow** [comment] 2018-12-04 21:20
it might be stored in task meta.. can't remember.

**Comment by mikebrow** [comment] 2018-12-05 17:07
@IRCody ok back.. digging through code.. 

1) the id is passed in when you create the container =  NewContainer(ctx, id, opts...)
2) when you create a task it is already there container.NewTask(ctx, ioCreation, taskOpts...)
3) in the task internals it assigns ContainerID to the id passed in (1) ContainerID: c.id,
4) When TaskExitEvents are created the ContainerID and ID should be the same value:	r.events.Publish(ctx, runtime.TaskExitEventTopic, &eventstypes.TaskExit{
		ContainerID: id,
		ID:          id,
		Pid:         uint32(pid),
		ExitStatus:  128 + uint32(unix.SIGKILL),
		ExitedAt:    exitedAt,
	})

**Comment by mikebrow** [comment] 2018-12-05 17:15
In short.. looks like at some point in time someone decided to change ID to ContainerID throughout the code and missed one. Then added ContainerID and had to leave the ID there. You'll note in your error log the containerid and id were both empty.

**Comment by IRCody** [comment] 2018-12-05 17:38
Thanks for digging.  I think there is definitely work for us to save the is
so we can pass back inside task exit event.  I wonder if that would be
enough to fix this issue on its own?

We are never calling new container/newtask directly since we are
implementing the shim interface but we do get the container Id with the rpc
calls. I wasn’t sure if we needed some other Id that was only being used by
cri.

**Comment by IRCody** [comment] 2018-12-05 17:40
I think the ids were empty Bc we are setting them to empty strings Bc we
don’t currently save the Id passed by containerd to us. I think this is
likely a one line change to set s.id = the Id we get from Rpc.

**Comment by mikebrow** [comment] 2018-12-05 20:06
wasn't sure what scenario you were running.. I updated your main to force id to be set when running from command line.

**Comment by mxpv** [comment] 2019-07-02 18:31
This is old :) I was able to run a few different containers with the plugin, so I believe there is no need to disable cri anymore. Closing.

**Closed by mxpv** 2019-07-02 18:31 UTC
Labels: kind/bug
