### ISSUE TITLE
Devmapper does not release the disk space upon device removal

### ISSUE THREAD

**Issue by ustiugov** [firecracker-microvm/firecracker-containerd#402] opened 2020-03-12 18:10 UTC
When I execute `dmsetup remove` on the snapshots, the disk space they allocated is not given back to the system for some reason (I do see that `/var/lib/firecracker-containerd/snapshotter` goes back to ~100MB but `df -h` does not show the freed up space).

**Host**: Ubuntu 18, 4.15; Firecracker version 0.21.0

**How to reproduce:**
* To create the thin pool of devices, I am using the commands from the quickstart guide. My script can be found [here](https://gist.github.com/ustiugov/6c24e8b49440b2249c1a458daadcfdbe)
* Pull several beefy docker/OCI images
* I remove the snapshots with the following commands:

```
for de in `sudo dmsetup ls| cut -f1|grep snap`; do sudo dmsetup remove $de && echo Removed $de; done
sudo dmsetup remove fc-dev-thinpool
```

I observe people have recently commented on a similar long-living issue with docker & devmapper
https://github.com/moby/moby/issues/3182#issuecomment-228298975

**Comment by mxpv** [comment] 2020-03-12 20:12
Could you also attach `dmesg` when you hit this problem? (curious if there are any messages related to devmapper).

**Comment by ustiugov** [comment] 2020-03-12 20:52
@mxpv This is what I can spot that seems related:

```
[116248.284096] veth0: Caught tx_queue_len zero misconfig
[116249.002884] EXT4-fs (dm-767): mounted filesystem with ordered data mode. Opts: (null)
[116249.069329] EXT4-fs (dm-767): mounted filesystem with ordered data mode. Opts: (null)
[116249.952479] EXT4-fs (dm-768): mounted filesystem with ordered data mode. Opts: (null)
[116250.009549] EXT4-fs (dm-768): mounted filesystem with ordered data mode. Opts: (null)
[116763.982753] Buffer I/O error on dev dm-1, logical block 2621424, async page read
[116764.201036] Buffer I/O error on dev dm-2, logical block 2621424, async page read
```

**Comment by ustiugov** [comment] 2021-01-20 12:45
@mxpv @kzys 

could we do something about this problem? this is really annoying when developing and must be a showstopper for production. Imagine that one needs to reboot a machine after every few 100s of VM boots.

**Comment by ustiugov** [comment] 2021-03-12 12:59
any news on that?

**Comment by alakesh** [comment] 2021-04-07 18:32
@ustiugov  can you please add some more details around what exactly you are seeing and what is the expected output? I would like to reproduce the problem the same way you did. Thanks

**Comment by ustiugov** [comment] 2021-04-09 12:11
hi @alakesh 

The problem is that after a VM is started and shut down repeatedly, followed by removing devmapper devices manually (if necessary), the amount of available storage on the root partition is less than in the beginning, as reported by `df -h`. 

Here is how I clean up the devices:
```
echo Removing devmapper devices
for de in `sudo dmsetup ls| cut -f1|grep thinpool`; do sudo dmsetup remove $de && echo Removed $de; done
sudo dmsetup remove fc-dev-thinpool

echo Cleaning /var/lib/firecracker-containerd/*
for d in containerd shim-base snapshotter; do sudo rm -rf /var/lib/firecracker-containerd/$d; done

echo Cleaning /run/firecracker-containerd/*
sudo rm -rf /run/firecracker-containerd/containerd.sock.ttrpc \
    /run/firecracker-containerd/io.containerd.runtime.v1.linux \
    /run/firecracker-containerd/io.containerd.runtime.v2.task
```

To reproduce the problem, one can repeatedly start and shutdown a VM using a quite large image. For example, one can use [logistic regression serving image](https://hub.docker.com/repository/docker/vhiveease/lr_serving) on DockerHub that uses Python scikit. One can try starting and shutting down VMs with firecracker-containerd while monitoring `df -h` output.

Please let me know if you need more details.

**Comment by Kern--** [comment] 2021-07-06 15:36
Hi @ustiugov 

I was able to reproduce this issue by launching just a simple busybox container, writing 500MB of random data, then following your steps to clean up the  thin-pool. I saw that the 500MB was not returned to my root filesystem. This is reproducible in both firecracker-containerd and upstream containerd. 

There are two issues that I think need addressing, but I'll start with the fact that you were still missing disk space after cleaning up the thin-pool. From your cleanup scripts, it looks like you did not detach the loopback devices.  Despite deleting the data and metadata files in `/var/lib/firecracker-containerd/snapshotter/devmapper`, the storage is still allocated by the loopback devices. If you run `sudo losetup -l` you should see 2 loopback devices where the underlying file has been deleted. If you run `sudo losetup -d $LOOPDEVICE` on those two devices, you should recover the lost disk space.

The second issue is that this is necessary at all. I dug through the docker issue and it appears that containerd has the same issue - on removal of a thin device, discards are not propagated to the underlying device. I submitted https://github.com/containerd/containerd/issues/5691 to address that.

Assuming that issue is taken up and a fix merged, the resulting behavior should be that after exiting a container, any disk space used by that container is immediately returned to the underlying device. 

Finally, I just want to clarify: from my testing, after exiting a container, the disk space was reused by future container launches. When I launched a container, wrote 500MB data, then exited the container, I only ever saw 500MB allocated in the underlying device. It did not grow unbounded. Can you confirm that you experienced the same behavior? If not I think there's something else to dig into. 

Please let me know if I missed anything or I'm describing a different issue than what you saw.

**Comment by kzys** [comment] 2022-01-14 18:04
@Kern-- you've fixed this issue on containerd. Do we need to upgrade containerd here to have the fix?

**Comment by Kern--** [comment] 2022-01-14 18:24
Yes, we can close this when we update to 1.6.

**Comment by Kern--** [comment] 2022-03-30 18:45
Resolved by https://github.com/firecracker-microvm/firecracker-containerd/pull/575

**Closed by Kern--** 2022-03-30 18:45 UTC
Labels: upstream/containerd
