### ISSUE TITLE
test namespace directory removal

### ISSUE THREAD

**Issue by FFMMM** [firecracker-microvm/firecracker-containerd#488] opened 2021-03-08 19:20 UTC
Similar to https://github.com/firecracker-microvm/firecracker-containerd/issues/415, we want to make sure that we are removing namespace directories on `StopVM()` correctly.

This issue's scope involves:

* assessing current behavior (resolution could be a no-op)
* identifying any test gaps and bridging that thru an integ or unit test
* making code changes needed to address a potential issue here.

**Comment by RoyceDavison** [comment] 2021-05-05 02:16
@kzys A quick question regarding [this line of code](https://github.com/firecracker-microvm/firecracker-containerd/blob/435ade47c5462cbf2e7decdbf12a9570ae5b474a/runtime/jailer_integ_test.go#L154), it seems that fcClient.StopVM() has already removed the namespace, otherwise the assertion couldn't be passed. Why do we need extra testings?

**Comment by kzys** [comment] 2021-05-05 23:56
The problem is we can remove `[namespace]/[vm ID]`, but nobody remove `[namespace]/` directory. We may need to check the remaining VMs in the directory, or change the directory structure to `[namespace][some separator except /][vm ID]`.

**Comment by RoyceDavison** [comment] 2021-05-06 06:43
> The problem is we can remove `[namespace]/[vm ID]`, but nobody remove `[namespace]/` directory. We may need to check the remaining VMs in the directory, or change the directory structure to `[namespace][some separator except /][vm ID]` rather than `[namespace]/[vm ID]`.

Got it, thanks. But I still a little bit confused. As you mentioned we don't remove `[namespace]/` directory. Then how it is possible that [this line of code](https://github.com/firecracker-microvm/firecracker-containerd/blob/435ade47c5462cbf2e7decdbf12a9570ae5b474a/runtime/jailer_integ_test.go#L154) returns an IsNotExist error? Since this test is passed, so that mean `assert.True(t, os.IsNotExist(err))` doesn't return any error. But as you mentioned above that, we don't remove `[namespace]/ `directory.

**Comment by kzys** [comment] 2021-05-06 16:20
The code removes `[namespace]/[vm ID]`, not `[namespace]/` itself.

**Comment by RoyceDavison** [comment] 2021-05-06 17:02
> The code removes `[namespace]/[vm ID]`, not `[namespace]/` itself.

Yeah, thanks. I made a mistake, didn't see vmID following it.

**Comment by RoyceDavison** [comment] 2021-06-14 17:44
Close the issue as this pr is merged https://github.com/firecracker-microvm/firecracker-containerd/pull/504

**Closed by RoyceDavison** 2021-06-14 17:44 UTC
Labels: exp/beginner
